## Arquivo SQL com os scripts de inserção de dados, respeitando as restrições de chaves estrangeiras

## PRODUTOS
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("CAMERA DE SEGURANCA",5,400.00,"XIAOMI MI HOME MJSXJ09CM 2K WIFI PANORAMICO 360 BRANCO","SIM","NAO",7);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("ASPIRADOR",2,200.00,"NAPPO NLAR-063 ROBOT WIFI 350ML PRETO","SIM","SIM",6);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("CAPTURA DE VIDEO",10,2050.00,"ELGATO THUNDERBOLT3 DOCK 4K 10DAA4101 TYPE-C/DP/LAN/USB3.1/SOM","NAO","NAO",5);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("BABA ELETRONICA ",1,350.00," MOTOROLA MBP87CNCT BRANCO/DOURADO","SIM","SIM",6);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("BATERIA",25,50.00,"GOLINE ALKALINE 9V 500MAH","SIM","SIM",5);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("CADEIRA GAMER",10,500.00,"HAVIT 922 GAMENOTE VERMELHO","SIM","SIM",4);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("MESA GAMER",16,1580.00,"MTEK GM01 LED RGB PRETO","SIM","NAO",4);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("TABLET",30,700.00,"AMAZON FIRE  HD8 KIDS EDITION 2GB/32GB AZUL WIFI/QUAD CORE 8","NAO","NAO",3);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("CONSOLE",40,5000.00,"SONY PS4 SLIM 1TB CUH-2215B PRETO BIVOLT","SIM","SIM",2);
INSERT INTO PRODUTOS (NOME,QUANT_ESTOQUE,PRECO,DESCRICAO,DISPONIVEL,DESTAQUE,IDDEPARTAMENTO) VALUES ("PENDRIVE",80,50.00,"8GB ADATA AC906-8GB USB 2.0  PRETO","SIM","NAO",1);

## CLIENTES
INSERT INTO CLIENTES(NOME,EMAIL,WHATSAPP,SENHA) VALUES("ITALO","ITALOSPORT110@HOTMAIL.COM","81988346853","ITALO142313");
INSERT INTO CLIENTES(NOME,EMAIL,WHATSAPP,SENHA) VALUES("MARCELO","MARCELO44@HOTMAIL.COM","81986376953","MARCELINHO22");
INSERT INTO CLIENTES(NOME,EMAIL,WHATSAPP,SENHA) VALUES("PEDRO","PEDRORYZEM5@GMAIL.COM","81985646883","RYZEN5");
INSERT INTO CLIENTES(NOME,EMAIL,WHATSAPP,SENHA) VALUES("HUANDERSOM","HUANDERSOM999@HOTMAIL.COM","81989306953","QWERT");
INSERT INTO CLIENTES(NOME,EMAIL,WHATSAPP,SENHA) VALUES("DIEGO","DIEGOXTRAP@HOTMAIL.COM","81984346533","TRGGG");

## ENDEREÇOS
INSERT INTO ENDERECOS(LOGRADURA,CEP,NUMERO,COMPLEMENTO,CIDADE,ESTADO,TIPOENDERECO,ENDERECOCLIENTE) VALUES("RUA BONGI",53510560,401,"POR TRÁS DA PADARIA","RECIFE","PE","RESIDENCIAL",1);
INSERT INTO ENDERECOS(LOGRADURA,CEP,NUMERO,COMPLEMENTO,CIDADE,ESTADO,TIPOENDERECO,ENDERECOCLIENTE) VALUES("Rua Benedito Fernandes Menozes 195",15405970,509,"EM FRETE AO TUDO JUNTO","Baguaçu","SP","COMERCIAL",2);
INSERT INTO ENDERECOS(LOGRADURA,CEP,NUMERO,COMPLEMENTO,CIDADE,ESTADO,TIPOENDERECO,ENDERECOCLIENTE) VALUES("Praça Venâncio Alves, s/n",46820971,420,"AO LADO MERCADO PRA","Bonito","BA","RESIDENCIAL",3);
INSERT INTO ENDERECOS(LOGRADURA,CEP,NUMERO,COMPLEMENTO,CIDADE,ESTADO,TIPOENDERECO,ENDERECOCLIENTE) VALUES("Quadra QNR 5 Conjunto O",72275680,200,"EM FRENTE AO TREVO","Brasília","DF","COMERCIAL",4);
INSERT INTO ENDERECOS(LOGRADURA,CEP,NUMERO,COMPLEMENTO,CIDADE,ESTADO,TIPOENDERECO,ENDERECOCLIENTE) VALUES("Rua Doutor Custódio de Paula Rodrigues 19",35365970,154,"AO LADO DO SHOPPING","Abre Campo","MG","RESIDENCIAL",5);

## PEDIDOS
INSERT INTO PEDIDOS(VALORPEDIDO,DATAPEDIDO,STATUSPEDIDO,PEDIDOSCLIENTES) VALUES(500.00,"2021-06-15","NOVO PEDIDO",1);
INSERT INTO PEDIDOS(VALORPEDIDO,DATAPEDIDO,STATUSPEDIDO,PEDIDOSCLIENTES) VALUES(2000.00,"2021-01-20","CANCELADO",2);
INSERT INTO PEDIDOS(VALORPEDIDO,DATAPEDIDO,STATUSPEDIDO,PEDIDOSCLIENTES) VALUES(1500.00,"2021-03-14","EM TRANSPORTE",3);
INSERT INTO PEDIDOS(VALORPEDIDO,DATAPEDIDO,STATUSPEDIDO,PEDIDOSCLIENTES) VALUES(5000.00,"2021-04-10","ENTREGUE",4);
INSERT INTO PEDIDOS(VALORPEDIDO,DATAPEDIDO,STATUSPEDIDO,PEDIDOSCLIENTES) VALUES(1050.00,"2021-02-22","PAGAMENTO AUTORIZADO",5);

## ITENS PEDIDOS
INSERT INTO ITENS_PEDIDOS(PRECO,QUANTIDADE,VALORTOTAL,PEDIDOS_ITENS,ITENS_PRODUTOS) VALUES(400.00,1,PRECO*QUANTIDADE,1,1);
INSERT INTO ITENS_PEDIDOS(PRECO,QUANTIDADE,VALORTOTAL,PEDIDOS_ITENS,ITENS_PRODUTOS) VALUES(200.00,3,PRECO*QUANTIDADE,2,2);
INSERT INTO ITENS_PEDIDOS(PRECO,QUANTIDADE,VALORTOTAL,PEDIDOS_ITENS,ITENS_PRODUTOS) VALUES(350.00,1,PRECO*QUANTIDADE,4,4);
INSERT INTO ITENS_PEDIDOS(PRECO,QUANTIDADE,VALORTOTAL,PEDIDOS_ITENS,ITENS_PRODUTOS) VALUES(50.00,3,PRECO*QUANTIDADE,5,5);